# Generated by Django 3.2.9 on 2021-11-28 22:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year_of_release', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(music.models.get_current_year)])),
                ('produced_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('first_appearance', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(music.models.get_current_year)], verbose_name='Year of first appearance')),
                ('last_appearance', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(music.models.get_current_year)], verbose_name='Year of last appearance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_style',
            new_name='style',
        ),
        migrations.RemoveField(
            model_name='song',
            name='author_website',
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('nationality', models.CharField(max_length=2)),
                ('instrument', models.CharField(choices=[('piano', 'Piano'), ('eguitar', 'Electric Guitar'), ('cguitar', 'Classical Guitar'), ('aguitar', 'Acoustic Guitar'), ('ebass', 'Electric Bass'), ('bass', 'Bass'), ('drums', 'Drums'), ('voice', 'Voice'), ('violin', 'Violin'), ('harp', 'Harp'), ('handpan', 'Handpan'), ('tambourine', 'Tambourine'), ('sax', 'Saxophone'), ('trumpet', 'Trumpet'), ('trombone', 'Trombone'), ('flute', 'Flute'), ('clarinet', 'Clarinet'), ('ukulele', 'Ukulele')], max_length=25)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='music.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.author'),
        ),
    ]
