# Generated by Django 5.0.2 on 2024-02-13 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_song_created_by_alter_song_last_modified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_style',
            field=models.CharField(choices=[('Indie', 'Indie'), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Funky', 'Funky'), ('Reggaeton', 'Reggaeton'), ('Classic', 'Classic'), ('Orquestra', 'Orquestra'), ('Folk', 'Folk')], max_length=25),
        ),
        migrations.AlterField(
            model_name='song',
            name='last_modified_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='l_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
