# Generated by Django 5.0.2 on 2024-02-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_alter_song_created_by_alter_song_last_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_style',
            field=models.CharField(choices=[('Indie', 'Indie'), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Funky', 'Funky'), ('Reggaeton', 'Reggaeton'), ('Classic', 'Classic'), ('Orquestra', 'Orquestra'), ('Folk', 'Folk')], max_length=30),
        ),
    ]
