# Generated by Django 5.0.2 on 2024-02-09 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, db_index=True, max_length=50)),
                ('author_website', models.URLField(blank=True)),
                ('album', models.CharField(blank=True, max_length=250)),
                ('duration', models.DurationField()),
                ('style', models.CharField(blank=True, choices=[('rock', 'Rock'), ('pop', 'Pop'), ('indie', 'Indie'), ('funky', 'Funky'), ('classic', 'Classic'), ('reggaeton', 'Reggaeton')], max_length=20)),
                ('playbacks', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(4.99)])),
                ('deal_of_the_day', models.BooleanField(blank=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('title', 'author', 'album', 'duration'), name='unique_song'),
        ),
    ]
