# Generated by Django 5.0.2 on 2024-02-09 22:02

import django.core.validators
import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('indie', 'Indie'), ('funky', 'Funky'), ('classic', 'Classic'), ('reggaeton', 'Reggaeton'), ('funky', 'Funky')], max_length=10)),
                ('audio', models.FileField(upload_to='audio/')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, db_index=True, max_length=50)),
                ('author_website', models.URLField(blank=True)),
                ('album', models.CharField(blank=True, max_length=250)),
                ('duration', models.DurationField()),
                ('song_style', models.CharField(blank=True, choices=[('rock', 'Rock'), ('pop', 'Pop'), ('indie', 'Indie'), ('funky', 'Funky'), ('classic', 'Classic'), ('reggaeton', 'Reggaeton'), ('funky', 'Funky')], max_length=20)),
                ('playbacks', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[music.models.price_validation])),
                ('deal_of_the_day', models.BooleanField(blank=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AddConstraint(
            model_name='audio',
            constraint=models.UniqueConstraint(fields=('title', 'author', 'album', 'duration'), name='unique_song'),
        ),
    ]



# python manage.py test  music.tests.test_task1

# python manage.py test  music.tests.test_task2